/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { basic } from "./basic";
import { oauth2 } from "./oauth2";

export default {
  basic,
  oauth2,
};
