/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { ConfigVarExpression } from "@prismatic-io/spectral";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";

export interface WebhookValues {}

/**
 * Trigger for handling webhook requests from the Salesforce platform. Returns the expected response to Salesforce and converts the XML payload to an object for more convenient use in the rest of the flow.
 *
 * @description Trigger for handling webhook requests from the Salesforce platform. Returns the expected response to Salesforce and converts the XML payload to an object for more convenient use in the rest of the flow.
 * This object is used to support type hinting.
 */
export const webhook = {
  key: "webhook",
  perform: <TReturn>(_values: WebhookValues): Promise<TReturn> =>
    Promise.resolve<TReturn>({} as TReturn),
  inputs: {},
} as const;

/**
 * Trigger for handling webhook requests from the Salesforce platform. Returns the expected response to Salesforce and converts the XML payload to an object for more convenient use in the rest of the flow. Trigger Helper
 *
 * @comments This wrapper function can be used directly in flow definitions.
 */
export const salesforceWebhook = (values: {}) => {
  return {
    get component() {
      const context = requireIntegrationContext();
      return findUserDefinedComponentKey(
        "salesforce",
        true,
        context.componentRegistry
      );
    },
    key: "webhook",
    values,
  } as const;
};
