/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateFolderValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Path
   * The location of a file within a Dropbox share. Include a leading \/.
   *
   * @example \/path\/to\/file.txt
   * @placeholder File Path
   */
  path: string;
}

/**
 * Create Folder
 *
 * @description Create a Folder at the specified path
 */
export const createFolder = {
  key: "createFolder",
  perform: async <TReturn>(values: CreateFolderValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.createFolder({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    path: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        metadata: {
          id: "exampleId",
          name: "myFolderName",
        },
      },
    },
  },
} as const;
