/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface CreateSharedLinkValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Path
   * The location of a file within a Dropbox share. Include a leading \/.
   *
   * @example \/path\/to\/file.txt
   * @placeholder File Path
   */
  path: string;
  /**
   * Require Password
   * Boolean flag to enable or disable password protection.
   *
   * @default false
   */
  require_password?: boolean;
  /**
   * Link Password
   * If the shared link has a password, this parameter can be used.
   *
   * @example anExamplePassword
   */
  link_password?: string;
  /**
   * Expires
   * Expiration time of the shared link. By default the link won't expire.
   *
   * @example 2021-01-01T00:00:00Z
   */
  expires?: string;
  /**
   * Audience
   *
   */
  audience: `public` | `team` | `no_one` | ``;
  /**
   * Access
   * Requested access level you want the audience to gain from this link. Note, modifying access level for an existing link is not supported.
   *
   */
  access?: `viewer` | `editor` | `default` | ``;
  /**
   * Allow Download
   * Boolean flag to allow or not download capabilities for shared links.
   *
   * @default false
   */
  allow_download?: boolean;
  /**
   * Team User Type
   * The type of user to connect with. Admin or User.
   *
   */
  userType?: `admin` | `user` | ``;
  /**
   * Team Member ID
   * The ID of the team member. Required if Team User Type is set.
   *
   * @example dbmid:abcd1234
   */
  teamMemberId?: string;
}

/**
 * Create Shared Link
 *
 * @description Create a shared link with custom settings. If no settings are given then the default visibility is RequestedVisibility.public (The resolved visibility, though, may depend on other aspects such as team and shared folder settings).
 */
export const createSharedLink = {
  key: "createSharedLink",
  perform: async <TReturn>(
    values: CreateSharedLinkValues,
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.createSharedLink({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    path: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    require_password: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    link_password: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    expires: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    audience: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    access: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    allow_download: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    userType: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    teamMemberId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        ".tag": "file",
        client_modified: "2015-05-12T15:50:38Z",
        id: "id:a4ayc_80_OEAAAAAAAAAXw",
        link_permissions: {
          allow_comments: true,
          allow_download: true,
          audience_options: [
            {
              allowed: true,
              audience: {
                ".tag": "public",
              },
            },
            {
              allowed: false,
              audience: {
                ".tag": "team",
              },
            },
            {
              allowed: true,
              audience: {
                ".tag": "no_one",
              },
            },
          ],
          can_allow_download: true,
          can_disallow_download: false,
          can_remove_expiry: false,
          can_remove_password: true,
          can_revoke: false,
          can_set_expiry: false,
          can_set_password: true,
          can_use_extended_sharing_controls: false,
          require_password: false,
          resolved_visibility: {
            ".tag": "public",
          },
          revoke_failure_reason: {
            ".tag": "owner_only",
          },
          team_restricts_comments: true,
          visibility_policies: [
            {
              allowed: true,
              policy: {
                ".tag": "public",
              },
              resolved_policy: {
                ".tag": "public",
              },
            },
            {
              allowed: true,
              policy: {
                ".tag": "password",
              },
              resolved_policy: {
                ".tag": "password",
              },
            },
          ],
        },
        name: "Prime_Numbers.txt",
        path_lower: "/homework/math/prime_numbers.txt",
        rev: "a1c10ce0dd78",
        server_modified: "2015-05-12T15:50:38Z",
        size: 7212,
        team_member_info: {
          display_name: "Roger Rabbit",
          member_id: "dbmid:abcd1234",
          team_info: {
            id: "dbtid:AAFdgehTzw7WlXhZJsbGCLePe8RvQGYDr-I",
            name: "Acme, Inc.",
          },
        },
        url: "https://www.dropbox.com/s/2sn712vy1ovegw8/Prime_Numbers.txt?dl=0",
      },
    },
  },
} as const;
