/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface DeleteObjectValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Path
   * The location of a file within a Dropbox share. Include a leading \/.
   *
   * @example \/path\/to\/file.txt
   * @placeholder File Path
   */
  path: string;
}

/**
 * Delete Object
 *
 * @description Delete a Folder or File at the specified path
 */
export const deleteObject = {
  key: "deleteObject",
  perform: async <TReturn>(values: DeleteObjectValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.deleteObject({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    path: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        metadata: {
          ".tag": "file",
          name: "myCopy",
          id: "exampleId",
          client_modified: "Wed, 01 Jan 2020 00:00:00 GMT",
          server_modified: "Wed, 01 Jan 2020 00:00:00 GMT",
          size: 2048,
        },
      },
    },
  },
} as const;
