/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface DownloadFileValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Path
   * The location of a file within a Dropbox share. Include a leading \/.
   *
   * @example \/path\/to\/file.txt
   * @placeholder File Path
   */
  path: string;
  /**
   * Download as Zip
   * Download a folder from the user's Dropbox, as a zip file. The folder must be less than 20 GB in size and any single file within must be less than 4 GB in size.
   *
   * @default false
   */
  download_as_zip?: boolean;
}

/**
 * Download File
 *
 * @description Download the file (< 150MB) at the specified path
 */
export const downloadFile = {
  key: "downloadFile",
  perform: async <TReturn>(values: DownloadFileValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.downloadFile({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    path: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    download_as_zip: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
  },
  examplePayload: {
    data: {
      type: "Buffer",
      data: [101, 120, 97, 109, 112, 108, 101],
    },
    contentType: "application/octet",
  },
} as const;
