/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ExportFileValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Directory Path
   * The path of the file to be exported.
   *
   * @example \/Homework\/math\/Prime_Numbers.gsheet
   * @placeholder Directory Path Prefix
   */
  path: string;
  /**
   * Team User Type
   * The type of user to connect with. Admin or User.
   *
   */
  userType?: `admin` | `user` | ``;
  /**
   * Team Member ID
   * The ID of the team member. Required if Team User Type is set.
   *
   * @example dbmid:abcd1234
   */
  teamMemberId?: string;
}

/**
 * Export File
 *
 * @description Export the file at the specified path
 */
export const exportFile = {
  key: "exportFile",
  perform: async <TReturn>(values: ExportFileValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.exportFile({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    path: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    userType: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    teamMemberId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        export_metadata: {
          export_hash:
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
          name: "Prime_Numbers.xlsx",
          size: 7189,
        },
        file_metadata: {
          client_modified: "2015-05-12T15:50:38Z",
          content_hash:
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
          file_lock_info: {
            created: "2015-05-12T15:50:38Z",
            is_lockholder: true,
            lockholder_name: "Imaginary User",
          },
          has_explicit_shared_members: false,
          id: "id:a4ayc_80_OEAAAAAAAAAXw",
          is_downloadable: true,
          name: "Prime_Numbers.txt",
          path_display: "/Homework/math/Prime_Numbers.txt",
          path_lower: "/homework/math/prime_numbers.txt",
          property_groups: [
            {
              fields: [
                {
                  name: "Security Policy",
                  value: "Confidential",
                },
              ],
              template_id: "ptid:1a5n2i6d3OYEAAAAAAAAAYa",
            },
          ],
          rev: "a1c10ce0dd78",
          server_modified: "2015-05-12T15:50:38Z",
          sharing_info: {
            modified_by: "dbid:AAH4f99T0taONIb-OurWxbNQ6ywGRopQngc",
            parent_shared_folder_id: "84528192421",
            read_only: true,
          },
          size: 7212,
        },
      },
    },
  },
} as const;
