/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetCurrentAccountValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
}

/**
 * Get Current Account
 *
 * @description Get information about the currently authenticated user
 */
export const getCurrentAccount = {
  key: "getCurrentAccount",
  perform: async <TReturn>(
    values: GetCurrentAccountValues,
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.getCurrentAccount({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
  },
  examplePayload: {
    data: {
      account_id: "dbid:EXAMPLE",
      name: {
        given_name: "John",
        surname: "Doe",
        familiar_name: "John",
        display_name: "John Doe",
        abbreviated_name: "JD",
      },
      email: "john.doe@example.com",
      email_verified: true,
      profile_photo_url: "",
      disabled: false,
      country: "US",
      locale: "en",
      referral_link: "",
      is_paired: true,
      account_type: {
        ".tag": "basic",
      },
      root_info: {
        ".tag": "user",
        root_namespace_id: "123456789",
        home_namespace_id: "123456789",
      },
    },
  },
} as const;
