/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetDownloadStatusValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Async Job ID
   * The ID of the asynchronous job. From the response of the Save From URL action would be a good place to get this value.
   *
   * @example nMvNReawvD4AAAAAAAAAAQ
   * @placeholder Async Job ID
   */
  asyncJobId: string;
}

/**
 * Get Download Status
 *
 * @description Get the status of a file download from a URL to Dropbox
 */
export const getDownloadStatus = {
  key: "getDownloadStatus",
  perform: async <TReturn>(
    values: GetDownloadStatusValues,
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.getDownloadStatus({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    asyncJobId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        ".tag": "in_progress",
      },
    },
  },
} as const;
