/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetMetadataValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Path
   * The path of a file or folder on Dropbox to get metadata for.
   *
   * @example id:a4ayc_80_OEAAAAAAAAAYa || \/Homework\/math
   * @placeholder File Path
   */
  path: string;
  /**
   * Include Media Info
   * If true, FileMetadata.media_info is set for photo and video.
   *
   * @default false
   */
  include_media_info?: boolean;
  /**
   * Include Deleted
   * DeletedMetadata will be returned for deleted file or folder, otherwise LookupError.not_found will be returned.
   *
   * @default false
   */
  include_deleted?: boolean;
  /**
   * Include Has Explicit Shared Members
   * If true, the results will include a flag for each file indicating whether or not that file has any explicit members.
   *
   * @default false
   */
  include_has_explicit_shared_members?: boolean;
  /**
   * Team User Type
   * The type of user to connect with. Admin or User.
   *
   */
  userType?: `admin` | `user` | ``;
  /**
   * Team Member ID
   * The ID of the team member. Required if Team User Type is set.
   *
   * @example dbmid:abcd1234
   */
  teamMemberId?: string;
}

/**
 * Get Metadata for File or Folder
 *
 * @description Returns the metadata for a file or folder.
 */
export const getMetadata = {
  key: "getMetadata",
  perform: async <TReturn>(values: GetMetadataValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.getMetadata({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    path: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    include_media_info: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    include_deleted: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    include_has_explicit_shared_members: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    userType: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    teamMemberId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        ".tag": "file",
        client_modified: "2015-05-12T15:50:38Z",
        content_hash:
          "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        file_lock_info: {
          created: "2015-05-12T15:50:38Z",
          is_lockholder: true,
          lockholder_name: "Imaginary User",
        },
        has_explicit_shared_members: false,
        id: "id:a4ayc_80_OEAAAAAAAAAXw",
        is_downloadable: true,
        name: "Prime_Numbers.txt",
        path_display: "/Homework/math/Prime_Numbers.txt",
        path_lower: "/homework/math/prime_numbers.txt",
        property_groups: [
          {
            fields: [
              {
                name: "Security Policy",
                value: "Confidential",
              },
            ],
            template_id: "ptid:1a5n2i6d3OYEAAAAAAAAAYa",
          },
        ],
        rev: "a1c10ce0dd78",
        server_modified: "2015-05-12T15:50:38Z",
        sharing_info: {
          modified_by: "dbid:AAH4f99T0taONIb-OurWxbNQ6ywGRopQngc",
          parent_shared_folder_id: "84528192421",
          read_only: true,
        },
        size: 7212,
      },
    },
  },
} as const;
