/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetSharedMetadataForFolderValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Shared Folder ID
   * The ID of the shared folder to retrieve metadata for.
   *
   * @example 84528192421
   */
  fileId: string;
  /**
   * Team User Type
   * The type of user to connect with. Admin or User.
   *
   */
  userType?: `admin` | `user` | ``;
  /**
   * Team Member ID
   * The ID of the team member. Required if Team User Type is set.
   *
   * @example dbmid:abcd1234
   */
  teamMemberId?: string;
}

/**
 * Get Shared Metadata for Folder
 *
 * @description Returns shared folder metadata.
 */
export const getSharedMetadataForFolder = {
  key: "getSharedMetadataForFolder",
  perform: async <TReturn>(
    values: GetSharedMetadataForFolderValues,
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.getSharedMetadataForFolder({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    fileId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    userType: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    teamMemberId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        access_inheritance: {
          ".tag": "inherit",
        },
        access_type: {
          ".tag": "owner",
        },
        is_inside_team_folder: false,
        is_team_folder: false,
        link_metadata: {
          audience_options: [
            {
              ".tag": "public",
            },
            {
              ".tag": "team",
            },
            {
              ".tag": "members",
            },
          ],
          current_audience: {
            ".tag": "public",
          },
          link_permissions: [
            {
              action: {
                ".tag": "change_audience",
              },
              allow: true,
            },
          ],
          password_protected: false,
          url: "",
        },
        name: "dir",
        path_lower: "/dir",
        permissions: [],
        policy: {
          acl_update_policy: {
            ".tag": "owner",
          },
          member_policy: {
            ".tag": "anyone",
          },
          resolved_member_policy: {
            ".tag": "team",
          },
          shared_link_policy: {
            ".tag": "anyone",
          },
        },
        preview_url: "https://www.dropbox.com/scl/fo/fir9vjelf",
        shared_folder_id: "84528192421",
        time_invited: "2016-01-20T00:00:00Z",
      },
    },
  },
} as const;
