/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetSharedMetadataForFileValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * File Id
   * The ID for the shared file.
   *
   * @example id:3kmLmQFnf1AAAAAAAAAAAw
   */
  fileId: string;
  /**
   * Team User Type
   * The type of user to connect with. Admin or User.
   *
   */
  userType?: `admin` | `user` | ``;
  /**
   * Team Member ID
   * The ID of the team member. Required if Team User Type is set.
   *
   * @example dbmid:abcd1234
   */
  teamMemberId?: string;
}

/**
 * Get Shared Metadata for File
 *
 * @description Returns shared file metadata.
 */
export const getSharedMetadataForFile = {
  key: "getSharedMetadataForFile",
  perform: async <TReturn>(
    values: GetSharedMetadataForFileValues,
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.getSharedMetadataForFile({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    fileId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    userType: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    teamMemberId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        access_type: {
          ".tag": "viewer",
        },
        id: "id:3kmLmQFnf1AAAAAAAAAAAw",
        name: "file.txt",
        owner_display_names: ["Jane Doe"],
        owner_team: {
          id: "dbtid:AAFdgehTzw7WlXhZJsbGCLePe8RvQGYDr-I",
          name: "Acme, Inc.",
        },
        path_display: "/dir/file.txt",
        path_lower: "/dir/file.txt",
        permissions: [],
        policy: {
          acl_update_policy: {
            ".tag": "owner",
          },
          member_policy: {
            ".tag": "anyone",
          },
          resolved_member_policy: {
            ".tag": "team",
          },
          shared_link_policy: {
            ".tag": "anyone",
          },
        },
        preview_url: "https://www.dropbox.com/scl/fi/fir9vjelf",
        time_invited: "2016-01-20T00:00:00Z",
      },
    },
  },
} as const;
