/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetSharedLinkFileValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Shared Link URL
   * StringURL of the shared link.
   *
   * @example https:\/\/www.dropbox.com\/s\/2sn712vy1ovegw8\/Prime_Numbers.txt?dl=0
   * @placeholder URL to Save
   */
  urlToSave: string;
  /**
   * Directory Path
   * If the shared link is to a folder, this parameter can be used to retrieve the metadata for a specific file or sub-folder in this folder. A relative path should be used.
   *
   * @example \/Homework\/math\/Prime_Numbers.gsheet
   * @placeholder Directory Path Prefix
   */
  path?: string;
  /**
   * Link Password
   * If the shared link has a password, this parameter can be used.
   *
   * @example anExamplePassword
   */
  link_password?: string;
  /**
   * Team User Type
   * The type of user to connect with. Admin or User.
   *
   */
  userType?: `admin` | `user` | ``;
  /**
   * Team Member ID
   * The ID of the team member. Required if Team User Type is set.
   *
   * @example dbmid:abcd1234
   */
  teamMemberId?: string;
}

/**
 * Get Shared Link File
 *
 * @description Download the shared link's file from a user's Dropbox.
 */
export const getSharedLinkFile = {
  key: "getSharedLinkFile",
  perform: async <TReturn>(
    values: GetSharedLinkFileValues,
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.getSharedLinkFile({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    urlToSave: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    path: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    link_password: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    userType: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    teamMemberId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        ".tag": "file",
        client_modified: "2015-05-12T15:50:38Z",
        id: "id:a4ayc_80_OEAAAAAAAAAXw",
        link_permissions: {
          allow_comments: true,
          allow_download: true,
          audience_options: [
            {
              allowed: true,
              audience: {
                ".tag": "public",
              },
            },
            {
              allowed: false,
              audience: {
                ".tag": "team",
              },
            },
            {
              allowed: true,
              audience: {
                ".tag": "no_one",
              },
            },
          ],
          can_allow_download: true,
          can_disallow_download: false,
          can_remove_expiry: false,
          can_remove_password: true,
          can_revoke: false,
          can_set_expiry: false,
          can_set_password: true,
          can_use_extended_sharing_controls: false,
          require_password: false,
          resolved_visibility: {
            ".tag": "public",
          },
          revoke_failure_reason: {
            ".tag": "owner_only",
          },
          team_restricts_comments: true,
          visibility_policies: [
            {
              allowed: true,
              policy: {
                ".tag": "public",
              },
              resolved_policy: {
                ".tag": "public",
              },
            },
            {
              allowed: true,
              policy: {
                ".tag": "password",
              },
              resolved_policy: {
                ".tag": "password",
              },
            },
          ],
        },
        name: "Prime_Numbers.txt",
        path_lower: "/homework/math/prime_numbers.txt",
        rev: "a1c10ce0dd78",
        server_modified: "2015-05-12T15:50:38Z",
        size: 7212,
        team_member_info: {
          display_name: "Roger Rabbit",
          member_id: "dbmid:abcd1234",
          team_info: {
            id: "dbtid:AAFdgehTzw7WlXhZJsbGCLePe8RvQGYDr-I",
            name: "Acme, Inc.",
          },
        },
        url: "https://www.dropbox.com/s/2sn712vy1ovegw8/Prime_Numbers.txt?dl=0",
      },
    },
  },
} as const;
