/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetTemporaryLinkValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Path
   * The path to the file you want a temporary link to.
   *
   * @example \/video.mp4
   * @placeholder \/video.mp4
   */
  path: string;
  /**
   * Team Member ID
   * Used to specify the user to act on behalf of.
   *
   * @example dbmid:abcd1234
   */
  teamMemberId?: string;
}

/**
 * Get Temporary Link
 *
 * @description Get a temporary link to stream content of a file.
 */
export const getTemporaryLink = {
  key: "getTemporaryLink",
  perform: async <TReturn>(
    values: GetTemporaryLinkValues,
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.getTemporaryLink({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    path: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    teamMemberId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        metadata: {
          name: "drums.jpg",
          path_lower: "/drums.jpg",
          path_display: "/drums.jpg",
          id: "id:kXzCDysyTmQAAAAAAAAAGw",
          client_modified: "2023-12-12T00:25:58Z",
          server_modified: "2023-12-12T00:25:59Z",
          rev: "60c45183ecb69f3e2a861",
          size: 175342,
          is_downloadable: true,
          content_hash:
            "2960e5e1f4e54e849d63862010035aea6d4f691aacc76abe5f33a80d670ec113",
        },
        link: "https://uc925b3fcc7a2208235a92b0e7e8.dl.dropboxusercontent.com/cd/0/get/COQEC7ffJgExogeJr8ngG5GH_4jW-iN6PC1heBZVwhZPs-3Wis_TJVR5GDHQnrLSuZRn8EhZVxFFxU9vOcpwZ2tbpIC59w1dQkaZ9Vs0q-8YPfD0hfLTOWy7iMpx5ymz6J9k6nnzHyr08sICt-RcM5jMk2ET8lwSQoQCeW6_TG6lWA/file",
      },
    },
  },
} as const;
