/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetTeamMembersValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Lookup By
   *
   */
  lookupKey: `email` | `team_member_id` | `external_id`;
  /**
   * Value
   *
   */
  lookupValue: string;
}

/**
 * Get Team Members
 *
 * @description Get Team Members by Member ID, External ID, or Email
 */
export const getTeamMembers = {
  key: "getTeamMembers",
  perform: async <TReturn>(values: GetTeamMembersValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.getTeamMembers({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    lookupKey: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    lookupValue: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        members_info: [
          {
            ".tag": "member_info",
            profile: {
              account_id: "dbid:AAH4f99T0taONIb-OurWxbNQ6ywGRopQngc",
              email: "tami@seagull.com",
              email_verified: false,
              external_id: "244423",
              groups: ["g:e2db7665347abcd600000000001a2b3c"],
              joined_on: "2015-05-12T15:50:38Z",
              member_folder_id: "20",
              membership_type: {
                ".tag": "full",
              },
              name: {
                abbreviated_name: "FF",
                display_name: "Franz Ferdinand (Personal)",
                familiar_name: "Franz",
                given_name: "Franz",
                surname: "Ferdinand",
              },
              profile_photo_url:
                "https://dl-web.dropbox.com/account_photo/get/dbaphid%3AAAHWGmIXV3sUuOmBfTz0wPsiqHUpBWvv3ZA?vers=1556069330102&size=128x128",
              secondary_emails: [
                {
                  email: "grape@strawberry.com",
                  is_verified: false,
                },
                {
                  email: "apple@orange.com",
                  is_verified: true,
                },
              ],
              status: {
                ".tag": "active",
              },
              team_member_id: "dbmid:FDFSVF-DFSDF",
            },
            roles: [
              {
                description: "Add, remove, and manage member accounts.",
                name: "User management admin",
                role_id: "pid_dbtmr:3456",
              },
            ],
          },
        ],
      },
    },
  },
} as const;
