/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetTemporaryUploadLinkValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Path
   * The location of a file within a Dropbox share. Include a leading \/.
   *
   * @example \/path\/to\/file.txt
   * @placeholder File Path
   */
  path: string;
  /**
   * Duration
   * How long the link will be valid, in seconds. Defaults to 1 hour.
   *
   * @default 3600
   */
  duration?: string;
}

/**
 * Get Temporary Upload Link
 *
 * @description Get a temporary presigned link to upload a file
 */
export const getTemporaryUploadLink = {
  key: "getTemporaryUploadLink",
  perform: async <TReturn>(
    values: GetTemporaryUploadLinkValues,
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.getTemporaryUploadLink({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    path: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    duration: {
      inputType: "string",
      collection: undefined,
      default: `3600`,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        link: "https://content.dropboxapi.com/...",
      },
    },
  },
} as const;
