/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { copyObject } from "./copyObject";
import { createFolder } from "./createFolder";
import { deleteObject } from "./deleteObject";
import { downloadFile } from "./downloadFile";
import { getCurrentAccount } from "./getCurrentAccount";
import { listChanges } from "./listChanges";
import { listFolder } from "./listFolder";
import { moveObject } from "./moveObject";
import { uploadFile } from "./uploadFile";
import { rawRequest } from "./rawRequest";
import { listSharingFolder } from "./listSharingFolder";
import { listTeamFolder } from "./listTeamFolder";
import { lockFile } from "./lockFile";
import { unlockFile } from "./unlockFile";
import { getFileLock } from "./getFileLock";
import { getTeamMembers } from "./getTeamMembers";
import { saveFromUrl } from "./saveFromUrl";
import { getDownloadStatus } from "./getDownloadStatus";
import { searchFiles } from "./searchFiles";
import { searchFolders } from "./searchFolders";
import { getSharedLinkFile } from "./getSharedLinkFile";
import { exportFile } from "./exportFile";
import { listSharedLinks } from "./listSharedLinks";
import { shareFolder } from "./shareFolder";
import { unshareFolder } from "./unshareFolder";
import { unshareFile } from "./unshareFile";
import { getMetadata } from "./getMetadata";
import { getSharedMetadataForFile } from "./getSharedMetadataForFile";
import { getSharedMetadataForFolder } from "./getSharedMetadataForFolder";
import { createSharedLink } from "./createSharedLink";
import { getTemporaryUploadLink } from "./getTemporaryUploadLink";
import { getTemporaryLink } from "./getTemporaryLink";

export default {
  copyObject,
  createFolder,
  deleteObject,
  downloadFile,
  getCurrentAccount,
  listChanges,
  listFolder,
  moveObject,
  uploadFile,
  rawRequest,
  listSharingFolder,
  listTeamFolder,
  lockFile,
  unlockFile,
  getFileLock,
  getTeamMembers,
  saveFromUrl,
  getDownloadStatus,
  searchFiles,
  searchFolders,
  getSharedLinkFile,
  exportFile,
  listSharedLinks,
  shareFolder,
  unshareFolder,
  unshareFile,
  getMetadata,
  getSharedMetadataForFile,
  getSharedMetadataForFolder,
  createSharedLink,
  getTemporaryUploadLink,
  getTemporaryLink,
};
