/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListTeamFolderValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Directory Path
   * The path to a directory within a Dropbox share. Include a leading \/.
   *
   * @example \/path\/to\/my\/directory\/
   * @placeholder Directory Path Prefix
   */
  path?: string;
  /**
   * Fetch All
   * When enabled, automatically fetches all pages of results. Cursor and Limit inputs are ignored when this is enabled.
   *
   * @default false
   */
  fetchAll?: boolean;
  /**
   * Cursor
   * Specify the cursor returned by your last call to list_folder or list_folder\/continue.
   *
   * @example lslTXFcbLQKkb0vP9Kgh5hy0Y0OnC7Z9ZPHPwPmMnxSk3eiDRMkct7D8E
   */
  cursor?: string;
  /**
   * Limit
   * The maximum number of results to return per request. Note: This is an approximate number and there can be slightly more entries returned in some cases.
   *
   * @example 25
   */
  limit?: string;
}

/**
 * List Team&#39;s Folders
 *
 * @description List Team's Folder contents
 */
export const listTeamFolder = {
  key: "listTeamFolder",
  perform: async <TReturn>(values: ListTeamFolderValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.listTeamFolder({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    path: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    fetchAll: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    cursor: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    limit: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        cursor: "ZtkX9_EHj3x7PMkVuFIhwKYXEpwpLwyxp9vMKomUhllil9q7eWiAu",
        has_more: false,
        team_folders: [
          {
            content_sync_settings: [
              {
                id: "id:a4ayc_80_OEAAAAAAAAAXw",
                sync_setting: {
                  ".tag": "default",
                },
              },
            ],
            is_team_shared_dropbox: false,
            name: "Marketing",
            status: {
              ".tag": "active",
            },
            sync_setting: {
              ".tag": "default",
            },
            team_folder_id: "123456789",
          },
        ],
      },
    },
  },
} as const;
