/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListChangesValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Directory Path
   * The path to a directory within a Dropbox share. Include a leading \/.
   *
   * @example \/path\/to\/my\/directory\/
   * @placeholder Directory Path Prefix
   */
  directoryPath?: string;
  /**
   * Recursive
   * If true, the response will contain contents of all subfolders.
   *
   * @default false
   */
  recursive?: boolean;
  /**
   * Include Deleted?
   * If true, the results will include entries for files and folders that used to exist but were deleted.
   *
   * @default false
   */
  includeDeleted?: boolean;
  /**
   * Team User Type
   * The type of user to connect with. Admin or User.
   *
   */
  userType?: `admin` | `user` | ``;
  /**
   * Team Member ID
   * The ID of the team member. Required if Team User Type is set.
   *
   * @example dbmid:abcd1234
   */
  teamMemberId?: string;
}

/**
 * List Changes
 *
 * @description List changes that have been made to files in this folder since the last time this action was run.
 */
export const listChanges = {
  key: "listChanges",
  perform: async <TReturn>(values: ListChangesValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.listChanges({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    directoryPath: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    recursive: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    includeDeleted: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    userType: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    teamMemberId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      entries: [
        {
          ".tag": "deleted",
          name: "my-old-image.png",
          path_lower: "/my-old-image.png",
          path_display: "/my-old-image.png",
        },
        {
          ".tag": "file",
          name: "my-new-image.png",
          path_lower: "/my-new-image.png",
          path_display: "/my-new-image.png",
          id: "id:BTY6k_2K8PAAAAAAAAAX9g",
          client_modified: "2022-12-12T21:39:30Z",
          server_modified: "2022-12-12T22:40:57Z",
          rev: "5efa9326918a601c39731",
          size: 1758021,
          is_downloadable: true,
          content_hash:
            "dc05a61ecd59d294da1e971c4e40a980b9042c633b7bc777367991a046d2b32d",
        },
      ],
      cursor: "AAFCBKRdVxEXAMPLE",
      has_more: false,
    },
    crossFlowState: {},
  },
} as const;
