/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListSharingFolderValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Directory Path
   * The path to a directory within a Dropbox share. Include a leading \/.
   *
   * @example \/path\/to\/my\/directory\/
   * @placeholder Directory Path Prefix
   */
  path: string;
  /**
   * Folder Actions
   * A list of \`FolderAction\`s corresponding to \`FolderPermission\`s that should appear in the response's SharedFolderMetadata.permissions field describing the actions the authenticated user can perform on the folder. This field is optional.
   *
   * @example disable_viewer_info
   * @placeholder Folder Action
   */
  folderActions?: Record<string, string> | { key: string; value: string }[];
  /**
   * Fetch All
   * When enabled, automatically fetches all pages of results. Cursor and Limit inputs are ignored when this is enabled.
   *
   * @default false
   */
  fetchAll?: boolean;
  /**
   * Cursor
   * Specify the cursor returned by your last call to list_folder or list_folder\/continue.
   *
   * @example lslTXFcbLQKkb0vP9Kgh5hy0Y0OnC7Z9ZPHPwPmMnxSk3eiDRMkct7D8E
   */
  cursor?: string;
  /**
   * Limit
   * The maximum number of results to return per request. Note: This is an approximate number and there can be slightly more entries returned in some cases.
   *
   * @example 25
   */
  limit?: string;
}

/**
 * List Shared Folders
 *
 * @description List Shared Folders contents
 */
export const listSharingFolder = {
  key: "listSharingFolder",
  perform: async <TReturn>(
    values: ListSharingFolderValues,
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.listSharingFolder({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    path: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    folderActions: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    fetchAll: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    cursor: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    limit: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        cursor: "ZtkX9_EHj3x7PMkVuFIhwKYXEpwpLwyxp9vMKomUhllil9q7eWiAu",
        entries: [
          {
            access_inheritance: {
              ".tag": "inherit",
            },
            access_type: {
              ".tag": "owner",
            },
            is_inside_team_folder: false,
            is_team_folder: false,
            link_metadata: {
              audience_options: [
                {
                  ".tag": "public",
                },
                {
                  ".tag": "team",
                },
                {
                  ".tag": "members",
                },
              ],
              current_audience: {
                ".tag": "public",
              },
              link_permissions: [
                {
                  action: {
                    ".tag": "change_audience",
                  },
                  allow: true,
                },
              ],
              password_protected: false,
              url: "",
            },
            name: "dir",
            path_lower: "/dir",
            permissions: [],
            policy: {
              acl_update_policy: {
                ".tag": "owner",
              },
              member_policy: {
                ".tag": "anyone",
              },
              resolved_member_policy: {
                ".tag": "team",
              },
              shared_link_policy: {
                ".tag": "anyone",
              },
            },
            preview_url: "https://www.dropbox.com/scl/fo/fir9vjelf",
            shared_folder_id: "84528192421",
            time_invited: "2016-01-20T00:00:00Z",
          },
        ],
      },
    },
  },
} as const;
