/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListSharedLinksValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Directory Path
   * The path to a directory within a Dropbox share. Include a leading \/.
   *
   * @example \/path\/to\/my\/directory\/
   * @placeholder Directory Path Prefix
   */
  path?: string;
  /**
   * Direct Only
   * Links to parent folders can be suppressed by setting direct_only to true.
   *
   * @default false
   */
  direct_only?: boolean;
  /**
   * Fetch All
   * When enabled, automatically fetches all pages of results. Cursor and Limit inputs are ignored when this is enabled.
   *
   * @default false
   */
  fetchAll?: boolean;
  /**
   * Cursor
   * Specify the cursor returned by your last call to list_folder or list_folder\/continue.
   *
   * @example lslTXFcbLQKkb0vP9Kgh5hy0Y0OnC7Z9ZPHPwPmMnxSk3eiDRMkct7D8E
   */
  cursor?: string;
  /**
   * Team User Type
   * The type of user to connect with. Admin or User.
   *
   */
  userType?: `admin` | `user` | ``;
  /**
   * Team Member ID
   * The ID of the team member. Required if Team User Type is set.
   *
   * @example dbmid:abcd1234
   */
  teamMemberId?: string;
}

/**
 * List Shared Links
 *
 * @description List Folder contents at the specified path
 */
export const listSharedLinks = {
  key: "listSharedLinks",
  perform: async <TReturn>(values: ListSharedLinksValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.listSharedLinks({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    path: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    direct_only: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    fetchAll: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    cursor: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    userType: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    teamMemberId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        cursor: "ZtkX9_EHj3x7PMkVuFIhwKYXEpwpLwyxp9vMKomUhllil9q7eWiAu",
        has_more: true,
        links: [
          {
            ".tag": "file",
            client_modified: "2015-05-12T15:50:38Z",
            id: "id:a4ayc_80_OEAAAAAAAAAXw",
            link_permissions: {
              allow_comments: true,
              allow_download: true,
              audience_options: [
                {
                  allowed: true,
                  audience: {
                    ".tag": "public",
                  },
                },
                {
                  allowed: false,
                  audience: {
                    ".tag": "team",
                  },
                },
                {
                  allowed: true,
                  audience: {
                    ".tag": "no_one",
                  },
                },
              ],
              can_allow_download: true,
              can_disallow_download: false,
              can_remove_expiry: false,
              can_remove_password: true,
              can_revoke: false,
              can_set_expiry: false,
              can_set_password: true,
              can_use_extended_sharing_controls: false,
              require_password: false,
              resolved_visibility: {
                ".tag": "public",
              },
              revoke_failure_reason: {
                ".tag": "owner_only",
              },
              team_restricts_comments: true,
              visibility_policies: [
                {
                  allowed: true,
                  policy: {
                    ".tag": "public",
                  },
                  resolved_policy: {
                    ".tag": "public",
                  },
                },
                {
                  allowed: true,
                  policy: {
                    ".tag": "password",
                  },
                  resolved_policy: {
                    ".tag": "password",
                  },
                },
              ],
            },
            name: "Prime_Numbers.txt",
            path_lower: "/homework/math/prime_numbers.txt",
            rev: "a1c10ce0dd78",
            server_modified: "2015-05-12T15:50:38Z",
            size: 7212,
            team_member_info: {
              display_name: "Roger Rabbit",
              member_id: "dbmid:abcd1234",
              team_info: {
                id: "dbtid:AAFdgehTzw7WlXhZJsbGCLePe8RvQGYDr-I",
                name: "Acme, Inc.",
              },
            },
            url: "https://www.dropbox.com/s/2sn712vy1ovegw8/Prime_Numbers.txt?dl=0",
          },
        ],
      },
    },
  },
} as const;
