/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListFolderValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Directory Path
   * The path to a directory within a Dropbox share. Include a leading \/.
   *
   * @example \/path\/to\/my\/directory\/
   * @placeholder Directory Path Prefix
   */
  path?: string;
  /**
   * Recursive
   * If true, the response will contain contents of all subfolders.
   *
   * @default false
   */
  recursive?: boolean;
  /**
   * Fetch All
   * When enabled, automatically fetches all pages of results. Cursor and Limit inputs are ignored when this is enabled.
   *
   * @default false
   */
  fetchAll?: boolean;
  /**
   * Cursor
   * Specify the cursor returned by your last call to list_folder or list_folder\/continue.
   *
   * @example lslTXFcbLQKkb0vP9Kgh5hy0Y0OnC7Z9ZPHPwPmMnxSk3eiDRMkct7D8E
   */
  cursor?: string;
  /**
   * Limit
   * The maximum number of results to return per request. Note: This is an approximate number and there can be slightly more entries returned in some cases.
   *
   * @example 25
   */
  limit?: string;
  /**
   * Team User Type
   * The type of user to connect with. Admin or User.
   *
   */
  userType?: `admin` | `user` | ``;
  /**
   * Team Member ID
   * The ID of the team member. Required if Team User Type is set.
   *
   * @example dbmid:abcd1234
   */
  teamMemberId?: string;
}

/**
 * List Folder
 *
 * @description List Folder contents at the specified path
 */
export const listFolder = {
  key: "listFolder",
  perform: async <TReturn>(values: ListFolderValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.listFolder({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    path: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    recursive: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    fetchAll: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    cursor: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    limit: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    userType: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    teamMemberId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        entries: [
          {
            ".tag": "folder",
            id: "exampleId",
            name: "MyExampleFolder",
            path_lower: "/myexamplefolder",
          },
          {
            ".tag": "file",
            id: "exampleId",
            name: "MyImage.jpg",
            path_lower: "/myexamplefolder/myimage.jpg",
            client_modified: "Wed, 01 Jan 2020 00:00:00 GMT",
            server_modified: "Wed, 01 Jan 2020 00:00:00 GMT",
            rev: "681a01c39731",
            size: 213654,
          },
        ],
        cursor:
          "hgL45HTslKOhj1_GEut-DVuaNs4xrXzpwQZRyJ0-KCW0wWMQ5DZu68__ULJa0zDcBp3ZrMlCj3-ZuOy4kjc9H2o7Ohk9UsId0sxVZrXFX",
        has_more: true,
      },
    },
  },
} as const;
