/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface MoveObjectValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * From Path
   * The location of a source file within a Dropbox share. Include a leading \/.
   *
   * @example \/path\/to\/source\/file.txt
   * @placeholder From Path
   */
  fromPath: string;
  /**
   * To Path
   * The location of a destination file within a Dropbox share. Include a leading \/.
   *
   * @example \/path\/to\/destination\/file.txt
   * @placeholder To Path
   */
  toPath: string;
}

/**
 * Move Object
 *
 * @description Move a Folder or File from one path to another
 */
export const moveObject = {
  key: "moveObject",
  perform: async <TReturn>(values: MoveObjectValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.moveObject({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    fromPath: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    toPath: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        metadata: {
          ".tag": "file",
          name: "myCopy",
          id: "exampleId",
          client_modified: "Wed, 01 Jan 2020 00:00:00 GMT",
          server_modified: "Wed, 01 Jan 2020 00:00:00 GMT",
          size: 2048,
        },
      },
    },
  },
} as const;
