/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface SaveFromUrlValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * To Path
   * The path with file name with extension where the URL will be saved to in Dropbox.
   *
   * @example \/path\/to\/file.txt
   * @placeholder To Path
   */
  toPath: string;
  /**
   * URL to Save
   * The URL to save to Dropbox.
   *
   * @example https:\/\/example.com\/file.txt
   * @placeholder URL to Save
   */
  urlToSave: string;
  /**
   * Wait Until Complete
   * Whether to wait for the operation to complete.
   *
   * @default false
   */
  waitUntilComplete?: boolean;
}

/**
 * Save From URL
 *
 * @description Save a file from a URL to Dropbox
 */
export const saveFromUrl = {
  key: "saveFromUrl",
  perform: async <TReturn>(values: SaveFromUrlValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.saveFromUrl({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    toPath: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    urlToSave: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    waitUntilComplete: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        ".tag": "async_job_id",
        async_job_id: "LnMobEc7XVEAAAAAAAAAAQ",
      },
    },
  },
} as const;
