/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface SearchFoldersValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Folder Name
   * The name of the folder to search for.
   *
   * @example My Folder
   * @placeholder File Name
   */
  query: string;
  /**
   * Directory Path
   * The path to a directory within a Dropbox share. Include a leading \/.
   *
   * @example \/path\/to\/my\/directory\/
   * @placeholder Directory Path Prefix
   */
  path?: string;
  /**
   * Fetch All
   * When enabled, automatically fetches all pages of results. Cursor and Limit inputs are ignored when this is enabled.
   *
   * @default false
   */
  fetchAll?: boolean;
  /**
   * Cursor
   * Specify the cursor returned by your last call to list_folder or list_folder\/continue.
   *
   * @example lslTXFcbLQKkb0vP9Kgh5hy0Y0OnC7Z9ZPHPwPmMnxSk3eiDRMkct7D8E
   */
  cursor?: string;
  /**
   * Limit
   * The maximum number of results to return per request. Note: This is an approximate number and there can be slightly more entries returned in some cases.
   *
   * @example 25
   */
  limit?: string;
  /**
   * Team User Type
   * The type of user to connect with. Admin or User.
   *
   */
  userType?: `admin` | `user` | ``;
  /**
   * Team Member ID
   * The ID of the team member. Required if Team User Type is set.
   *
   * @example dbmid:abcd1234
   */
  teamMemberId?: string;
}

/**
 * Search Folders
 *
 * @description Search for folders at the specified path
 */
export const searchFolders = {
  key: "searchFolders",
  perform: async <TReturn>(values: SearchFoldersValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.searchFolders({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    query: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    path: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    fetchAll: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    cursor: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    limit: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    userType: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    teamMemberId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        has_more: false,
        matches: [
          {
            metadata: {
              ".tag": "metadata",
              metadata: {
                ".tag": "file",
                client_modified: "2015-05-12T15:50:38Z",
                content_hash:
                  "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                has_explicit_shared_members: false,
                id: "id:a4ayc_80_OEAAAAAAAAAXw",
                is_downloadable: true,
                name: "Prime_Numbers.txt",
                path_display: "/Homework/math/Prime_Numbers.txt",
                path_lower: "/homework/math/prime_numbers.txt",
                rev: "a1c10ce0dd78",
                server_modified: "2015-05-12T15:50:38Z",
                sharing_info: {
                  modified_by: "dbid:AAH4f99T0taONIb-OurWxbNQ6ywGRopQngc",
                  parent_shared_folder_id: "84528192421",
                  read_only: true,
                },
                size: 7212,
              },
            },
          },
        ],
      },
    },
  },
} as const;
