/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ShareFolderValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Directory Path
   * The path or the file id to the folder to share. If it does not exist, then a new one is created.
   *
   * @example \/example\/workspace
   * @placeholder Directory Path Prefix
   */
  path?: string;
  /**
   * ACL Update Policy
   * Who can add and remove members of this shared folder.
   *
   */
  acl_update_policy?: `owner` | `editors` | ``;
  /**
   * Force Async
   * Whether to force the share to happen asynchronously. .
   *
   * @default false
   */
  force_async?: boolean;
  /**
   * Member Policy
   * Who can be a member of this shared folder. Only applicable if the current user is on a team.
   *
   */
  member_policy?: `team` | `anyone` | `team_and_approved` | ``;
  /**
   * Shared Link Policy
   * The policy to apply to shared links created for content inside this shared folder. The current user must be on a team to set this policy to SharedLinkPolicy.members.
   *
   */
  shared_link_policy?: `team` | `anyone` | `members` | ``;
  /**
   * Viewer Info Policy
   * Who can enable\/disable viewer info for this shared folder.
   *
   */
  viewer_info_policy?: `enabled` | `disabled` | ``;
  /**
   * Access Inheritance
   * The access inheritance settings for the folder. .
   *
   */
  access_inheritance?: `inherit` | `no_inherit` | ``;
  /**
   * Actions
   * A list of \`FolderAction\`s corresponding to \`FolderPermission\`s that should appear in the response's SharedFolderMetadata.permissions field describing the actions the authenticated user can perform on the folder.
   *
   * @default []
   */
  actions?: (
    | `change_options`
    | `disable_viewer_info`
    | `edit_contents`
    | `enable_viewer_info`
    | `invite_editor`
    | `invite_viewer`
    | `invite_viewer_no_comment`
    | `relinquish_membership`
    | `unmount`
    | `unshare`
    | `leave_a_copy`
    | `share_linkdeprecated`
    | `create_linkdeprecated`
    | `create_view_link`
    | `create_edit_link`
    | `set_access_inheritance`
    | ``
  )[];
  /**
   * Team User Type
   * The type of user to connect with. Admin or User.
   *
   */
  userType?: `admin` | `user` | ``;
  /**
   * Team Member ID
   * The ID of the team member. Required if Team User Type is set.
   *
   * @example dbmid:abcd1234
   */
  teamMemberId?: string;
}

/**
 * Share Folder
 *
 * @description Share a folder with collaborators. Most sharing will be completed synchronously. Large folders will be completed asynchronously.
 */
export const shareFolder = {
  key: "shareFolder",
  perform: async <TReturn>(values: ShareFolderValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.shareFolder({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    path: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    acl_update_policy: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    force_async: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    member_policy: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    shared_link_policy: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    viewer_info_policy: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    access_inheritance: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    actions: {
      inputType: "string",
      collection: "valuelist",
      default: `[]`,
    },
    userType: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    teamMemberId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        ".tag": "complete",
        access_inheritance: {
          ".tag": "inherit",
        },
        access_type: {
          ".tag": "owner",
        },
        is_inside_team_folder: false,
        is_team_folder: false,
        link_metadata: {
          audience_options: [
            {
              ".tag": "public",
            },
            {
              ".tag": "team",
            },
            {
              ".tag": "members",
            },
          ],
          current_audience: {
            ".tag": "public",
          },
          link_permissions: [
            {
              action: {
                ".tag": "change_audience",
              },
              allow: true,
            },
          ],
          password_protected: false,
          url: "",
        },
        name: "dir",
        path_lower: "/dir",
        permissions: [],
        policy: {
          acl_update_policy: {
            ".tag": "owner",
          },
          member_policy: {
            ".tag": "anyone",
          },
          resolved_member_policy: {
            ".tag": "team",
          },
          shared_link_policy: {
            ".tag": "anyone",
          },
        },
        preview_url: "https://www.dropbox.com/scl/fo/fir9vjelf",
        shared_folder_id: "84528192421",
        time_invited: "2016-01-20T00:00:00Z",
      },
    },
  },
} as const;
