/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface UnlockFileValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Team User Type
   * The type of user to connect with. Admin or User.
   *
   */
  userType?: `admin` | `user` | ``;
  /**
   * Team Member ID
   * The ID of the team member. Required if Team User Type is set.
   *
   * @example dbmid:abcd1234
   */
  teamMemberId?: string;
  /**
   * File Path
   * This represents the source files's path. Include a leading \/ (Use this, Dynamic Paths or both).
   *
   * @example \/path\/to\/source\/file.txt
   * @placeholder File Path
   */
  filePaths?: string[];
  /**
   * Dynamic Paths
   * An optional list of paths (Use this, File Paths or both).
   *
   * @example [\\"\/path\/to\/file\\", \\"\/path\/to\/another\/file\\"]
   */
  dynamicPaths?: string;
}

/**
 * Unlock File
 *
 * @description Unlock the files at the given paths
 */
export const unlockFile = {
  key: "unlockFile",
  perform: async <TReturn>(values: UnlockFileValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.unlockFile({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    userType: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    teamMemberId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    filePaths: {
      inputType: "string",
      collection: "valuelist",
      default: [],
    },
    dynamicPaths: {
      inputType: "data",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        entries: [
          {
            ".tag": "success",
            lock: {
              content: {
                ".tag": "single_user",
                created: "2015-05-12T15:50:38Z",
                lock_holder_account_id:
                  "dbid:AAH4f99T0taONIb-OurWxbNQ6ywGRopQngc",
                lock_holder_team_id: "dbtid:1234abcd",
              },
            },
            metadata: {
              ".tag": "file",
              client_modified: "2015-05-12T15:50:38Z",
              content_hash:
                "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
              file_lock_info: {
                created: "2015-05-12T15:50:38Z",
                is_lockholder: true,
                lockholder_name: "Imaginary User",
              },
              has_explicit_shared_members: false,
              id: "id:a4ayc_80_OEAAAAAAAAAXw",
              is_downloadable: true,
              name: "Prime_Numbers.txt",
              path_display: "/Homework/math/Prime_Numbers.txt",
              path_lower: "/homework/math/prime_numbers.txt",
              property_groups: [
                {
                  fields: [
                    {
                      name: "Security Policy",
                      value: "Confidential",
                    },
                  ],
                  template_id: "ptid:1a5n2i6d3OYEAAAAAAAAAYa",
                },
              ],
              rev: "a1c10ce0dd78",
              server_modified: "2015-05-12T15:50:38Z",
              sharing_info: {
                modified_by: "dbid:AAH4f99T0taONIb-OurWxbNQ6ywGRopQngc",
                parent_shared_folder_id: "84528192421",
                read_only: true,
              },
              size: 7212,
            },
          },
        ],
      },
    },
  },
} as const;
