/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface UnshareFolderValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Shared Folder ID
   * The ID for the shared folder.
   *
   * @example 84528192421
   */
  shared_folder_id: string;
  /**
   * Leave a Copy
   * If true, members of this shared folder will get a copy of this folder after it's unshared. Otherwise, it will be removed from their Dropbox. The current user, who is an owner, will always retain their copy.
   *
   * @default false
   */
  leave_a_copy?: boolean;
  /**
   * Team User Type
   * The type of user to connect with. Admin or User.
   *
   */
  userType?: `admin` | `user` | ``;
  /**
   * Team Member ID
   * The ID of the team member. Required if Team User Type is set.
   *
   * @example dbmid:abcd1234
   */
  teamMemberId?: string;
}

/**
 * Unshare Folder
 *
 * @description Allows a shared folder owner to unshare the folder. Unshare will not work in following cases: The shared folder contains shared folders OR the shared folder is inside another shared folder.
 */
export const unshareFolder = {
  key: "unshareFolder",
  perform: async <TReturn>(values: UnshareFolderValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.unshareFolder({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    shared_folder_id: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    leave_a_copy: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    userType: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    teamMemberId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        ".tag": "complete",
      },
    },
  },
} as const;
