/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface UnshareFileValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * File Id
   * The ID for the shared file.
   *
   * @example id:3kmLmQFnf1AAAAAAAAAAAw
   */
  fileId: string;
  /**
   * Team User Type
   * The type of user to connect with. Admin or User.
   *
   */
  userType?: `admin` | `user` | ``;
  /**
   * Team Member ID
   * The ID of the team member. Required if Team User Type is set.
   *
   * @example dbmid:abcd1234
   */
  teamMemberId?: string;
}

/**
 * Unshare File
 *
 * @description Remove all members from this file. Does not remove inherited members.
 */
export const unshareFile = {
  key: "unshareFile",
  perform: async <TReturn>(values: UnshareFileValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.unshareFile({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    fileId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    userType: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    teamMemberId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: null,
    },
  },
} as const;
