/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface UploadFileValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Path
   * The location of a file within a Dropbox share. Include a leading \/.
   *
   * @example \/path\/to\/file.txt
   * @placeholder File Path
   */
  path: string;
  /**
   * File Contents
   * The contents to write to a file. This can be a string of text, it can be binary data (like an image or PDF) that was generated in a previous step.
   *
   * @example My File Contents
   * @placeholder Output data from previous step
   */
  fileContents: string;
}

/**
 * Upload File
 *
 * @description Upload a file to the specified path
 */
export const uploadFile = {
  key: "uploadFile",
  perform: async <TReturn>(values: UploadFileValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.dropbox.uploadFile({
      ...values,
    })) as TReturn;
  },
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    path: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    fileContents: {
      inputType: "data",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {
    data: {
      status: 200,
      headers: {},
      result: {
        id: "exampleId",
        client_modified: "Wed, 01 Jan 2020 00:00:00 GMT",
        server_modified: "Wed, 01 Jan 2020 00:00:00 GMT",
        size: 2048,
        name: "myFileName",
      },
    },
  },
} as const;
