/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { listFolders } from "./listFolders";
import { listSharedFolders } from "./listSharedFolders";
import { listTeamFolders } from "./listTeamFolders";

export default {
  listFolders,
  listSharedFolders,
  listTeamFolders,
};
