/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Directory Path
   * The path to a directory within a Dropbox share. Include a leading \/.
   *
   * @example \/path\/to\/my\/directory\/
   * @placeholder Directory Path Prefix
   */
  path?: string;
  /**
   * Cursor
   * Specify the cursor returned by your last call to list_folder or list_folder\/continue.
   *
   * @example lslTXFcbLQKkb0vP9Kgh5hy0Y0OnC7Z9ZPHPwPmMnxSk3eiDRMkct7D8E
   */
  cursor?: string;
  /**
   * Limit
   * The maximum number of results to return per request. Note: This is an approximate number and there can be slightly more entries returned in some cases.
   *
   * @example 25
   */
  limit?: string;
  /**
   * Folder Actions
   * A list of \`FolderAction\`s corresponding to \`FolderPermission\`s that should appear in the response's SharedFolderMetadata.permissions field describing the actions the authenticated user can perform on the folder. This field is optional.
   *
   * @example disable_viewer_info
   * @placeholder Folder Action
   */
  folderActions?: Record<string, string> | { key: string; value: string }[];
}

/**
 * List Shared Folders
 *
 * @description Fetch an array of shared folders
 * This object is used to support type hinting.
 */
export const listSharedFolders = {
  key: "listSharedFolders",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "picklist",
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    path: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    cursor: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    limit: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    folderActions: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
  },
} as const;

/**
 * List Shared Folders DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const dropboxListSharedFolders = (
  stableKey: string,
  values: {
    connection: ConfigVarExpression;
    path?: { value: string } | TemplateExpression | ConfigVarExpression;
    cursor?: { value: string } | TemplateExpression | ConfigVarExpression;
    limit?: { value: string } | TemplateExpression | ConfigVarExpression;
    folderActions?:
      | {
          value: Record<string, string> | { key: string; value: string }[];
        }
      | TemplateExpression
      | ConfigVarExpression;
  },
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "dropbox",
          true,
          context.componentRegistry,
        );
      },
      key: "listSharedFolders",
      values,
    },
  });
};
