/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dataSourceConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  TemplateExpression,
  Connection,
} from "@prismatic-io/spectral/dist/types";

export interface Values {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Directory Path
   * The path to a directory within a Dropbox share. Include a leading \/.
   *
   * @example \/path\/to\/my\/directory\/
   * @placeholder Directory Path Prefix
   */
  path?: string;
  /**
   * Cursor
   * Specify the cursor returned by your last call to list_folder or list_folder\/continue.
   *
   * @example lslTXFcbLQKkb0vP9Kgh5hy0Y0OnC7Z9ZPHPwPmMnxSk3eiDRMkct7D8E
   */
  cursor?: string;
  /**
   * Limit
   * The maximum number of results to return per request. Note: This is an approximate number and there can be slightly more entries returned in some cases.
   *
   * @example 25
   */
  limit?: string;
  /**
   * Recursive
   * If true, the response will contain contents of all subfolders.
   *
   * @default false
   */
  recursive?: boolean;
  /**
   * Team User Type
   * The type of user to connect with. Admin or User.
   *
   * @example either 'admin' or 'user'
   * @placeholder 'admin' or 'user'
   */
  userType?: `admin` | `user` | ``;
  /**
   * Team Member ID
   * The ID of the team member. Required if Team User Type is set.
   *
   * @example dbmid:abcd1234
   */
  teamMemberId?: string;
  /**
   * Entry Filter
   * Select a filter to return only files or folders. If both are selected, all will be returned.
   *
   * @default all
   */
  entryFilter?: `file` | `folder` | `all`;
}

/**
 * List Folders
 *
 * @description Fetch an array of folders
 * This object is used to support type hinting.
 */
export const listFolders = {
  key: "listFolders",
  perform: (_values: Values): Promise<void> => Promise.resolve(),
  dataSourceType: "picklist",
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    path: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    cursor: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    limit: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    recursive: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    userType: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    teamMemberId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    entryFilter: {
      inputType: "string",
      collection: undefined,
      default: `all`,
    },
  },
} as const;

/**
 * List Folders DataSource Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const dropboxListFolders = (
  stableKey: string,
  values: {
    connection: ConfigVarExpression;
    path?: { value: string } | TemplateExpression | ConfigVarExpression;
    cursor?: { value: string } | TemplateExpression | ConfigVarExpression;
    limit?: { value: string } | TemplateExpression | ConfigVarExpression;
    recursive?: { value: boolean } | TemplateExpression | ConfigVarExpression;
    userType?:
      | { value: `admin` | `user` | `` }
      | TemplateExpression
      | ConfigVarExpression;
    teamMemberId?: { value: string } | TemplateExpression | ConfigVarExpression;
    entryFilter?:
      | { value: `file` | `folder` | `all` }
      | TemplateExpression
      | ConfigVarExpression;
  },
) => {
  return dataSourceConfigVar({
    stableKey,
    dataSource: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "dropbox",
          true,
          context.componentRegistry,
        );
      },
      key: "listFolders",
      values,
    },
  });
};
