/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface GetQueryJobResultsValues {
  /**
   * Connection
   *
   */
  connection: Connection;
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Query Job Id
   *
   */
  queryJobId: string;
  /**
   * Locator
   *
   */
  locator?: string;
  /**
   * Max Records
   *
   */
  maxRecords?: string;
}

/**
 * Get Results for a Bulk Query Job
 *
 * @description Gets the results for a query job. The job must be in a Job Complete state
 */
export const getQueryJobResults = {
  key: "getQueryJobResults",
  perform: async <TReturn>(
    values: GetQueryJobResultsValues
  ): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.getQueryJobResults({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    queryJobId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    locator: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    maxRecords: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
  examplePayload: {
    data: '\n  "Id","Name"\n"005R0000000UyrWIAS","Jane Dunn"\n"005R0000000GiwjIAC","George Wright"\n"005R0000000GiwoIAC","Pat Wilson"\n',
  },
} as const;
