/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListLeadsValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Dynamic Fields
   *
   */
  dynamicValues?: string;
  /**
   * Field Values
   *
   */
  fieldValues?: Record<string, string> | Array<{ key: string; value: string }>;
  /**
   * Field Value Types
   *
   */
  fieldValueTypes?:
    | Record<string, string>
    | Array<{ key: string; value: string }>;
  /**
   * Page Size
   *
   */
  pageSize?: string;
  /**
   * Page Number
   *
   */
  pageNumber?: string;
  /**
   * Sort Criteria
   *
   */
  sort?: string;
  /**
   * Fetch All
   *
   * @default false
   */
  fetchAll?: boolean;
  /**
   * Max Records To Fetch
   *
   * @default 20000
   */
  maxRecordsToFetch?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * List Leads
 *
 * @description List all lead records
 */
export const listLeads = {
  key: "listLeads",
  perform: async <TReturn>(values: ListLeadsValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.listLeads({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    dynamicValues: {
      inputType: "code",
      collection: undefined,
      default: ``,
    },
    fieldValues: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    fieldValueTypes: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    pageSize: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    pageNumber: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    sort: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    fetchAll: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    maxRecordsToFetch: {
      inputType: "string",
      collection: undefined,
      default: `20000`,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: [
      {
        Id: "asdadasdad123",
        City: "Tampa",
        Name: "test2 test",
        State: "Florida",
        Title: "CTO",
        Status: "Open - Not Contacted",
        Street: null,
        Address: {
          city: "Tampa",
          state: "Florida",
          street: null,
          country: null,
          latitude: null,
          longitude: null,
          postalCode: null,
          geocodeAccuracy: null,
        },
        Company: "Test2 123",
        OwnerId: "asdadDSAFd1123",
        LastName: "test",
        PhotoUrl: "/services/images/photo/asdadasdad123",
        FirstName: "test2",
        IsDeleted: false,
        Salutation: null,
        attributes: {
          url: "/services/data/v53.0/sobjects/Lead/asdadasdad123",
          type: "Lead",
        },
        CleanStatus: "Pending",
        CreatedById: "asdadDSAFd1123",
        CreatedDate: "2023-10-05T15:39:28.000+0000",
        MasterRecordId: null,
        LastModifiedById: "asdadDSAFd1123",
        LastModifiedDate: "2023-10-05T15:39:28.000+0000",
        test__New_Test_Field__c: null,
      },
    ],
  },
} as const;
