/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListProfilesValues {
  /**
   * Version
   *
   * @default 63.0
   */
  version?: string;
  /**
   * Dynamic Fields
   *
   */
  dynamicValues?: string;
  /**
   * Field Values
   *
   */
  fieldValues?: Record<string, string> | Array<{ key: string; value: string }>;
  /**
   * Field Value Types
   *
   */
  fieldValueTypes?:
    | Record<string, string>
    | Array<{ key: string; value: string }>;
  /**
   * Page Size
   *
   */
  pageSize?: string;
  /**
   * Page Number
   *
   */
  pageNumber?: string;
  /**
   * Sort Criteria
   *
   */
  sort?: string;
  /**
   * Fetch All
   *
   * @default false
   */
  fetchAll?: boolean;
  /**
   * Max Records To Fetch
   *
   * @default 20000
   */
  maxRecordsToFetch?: string;
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * List Profiles
 *
 * @description List all profile records
 */
export const listProfiles = {
  key: "listProfiles",
  perform: async <TReturn>(values: ListProfilesValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.salesforce.listProfiles({
      ...values,
    })) as TReturn;
  },
  inputs: {
    version: {
      inputType: "string",
      collection: undefined,
      default: `63.0`,
    },
    dynamicValues: {
      inputType: "code",
      collection: undefined,
      default: ``,
    },
    fieldValues: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    fieldValueTypes: {
      inputType: "string",
      collection: "keyvaluelist",
      default: [],
    },
    pageSize: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    pageNumber: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    sort: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    fetchAll: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    maxRecordsToFetch: {
      inputType: "string",
      collection: undefined,
      default: `20000`,
    },
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {
    data: {
      results: [
        {
          Id: "DSDSDJSJD123123",
          Name: "Minimum Access - API Only Integrations",
          UserType: "Standard",
          attributes: {
            url: "/services/data/v53.0/sobjects/Profile/DSDSDJSJD123123",
            type: "Profile",
          },
          CreatedById: "asdsad12313",
          CreatedDate: "2024-02-10T07:08:00.000+0000",
          Description: null,
          UserLicenseId: "asdaskda123",
          LastViewedDate: null,
          SystemModstamp: "2024-10-29T18:23:13.000+0000",
          LastModifiedById: "fsadasd1233",
          LastModifiedDate: "2024-10-29T18:23:13.000+0000",
          LastReferencedDate: null,
        },
      ],
    },
  },
} as const;
