/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { connectionConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  ConfigVarVisibility,
} from "@prismatic-io/spectral/dist/types";

export interface OauthValues {
  /**
   * App Key
   * Generate in the [Dropbox Developer Portal](https:\/\/www.dropbox.com\/developers\/apps).
   *
   * @placeholder App Key
   */
  clientId: string;
  /**
   * App Secret
   * Generate in the [Dropbox Developer Portal](https:\/\/www.dropbox.com\/developers\/apps).
   *
   * @placeholder App Secret
   */
  clientSecret: string;
}

/**
 * OAuth 2.0
 *
 * @comments OAuth 2.0 Connectivity for Dropbox
 * This object is used to support type hinting.
 */
export const oauth = {
  key: "oauth",
  perform: (_values: OauthValues): Promise<void> => Promise.resolve(),
  inputs: {
    clientId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    clientSecret: {
      inputType: "password",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;

/**
 * OAuth 2.0 Connection Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const dropboxOauth = (
  stableKey: string,
  values: {
    clientId: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
    clientSecret: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
  },
) => {
  return connectionConfigVar({
    dataType: "connection",
    stableKey,
    connection: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "dropbox",
          true,
          context.componentRegistry,
        );
      },
      key: "oauth",
      values,
    },
  });
};
