/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { ConfigVarExpression } from "@prismatic-io/spectral";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";

export interface DropboxWebhookValues {
  /**
   * Signing Secret
   * The 'App Secret' of your Dropbox app.
   *
   */
  signingSecret: string;
}

/**
 * Receive and validate webhook requests from Dropbox for webhooks you configure.
 *
 * @description Receive and validate webhook requests from Dropbox for webhooks you configure.
 * This object is used to support type hinting.
 */
export const dropboxWebhook = {
  key: "dropboxWebhook",
  perform: <TReturn>(_values: DropboxWebhookValues): Promise<TReturn> =>
    Promise.resolve<TReturn>({} as TReturn),
  inputs: {
    signingSecret: {
      inputType: "password",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;

/**
 * Receive and validate webhook requests from Dropbox for webhooks you configure. Trigger Helper
 *
 * @comments This wrapper function can be used directly in flow definitions.
 */
export const dropboxDropboxWebhook = (values: {
  signingSecret:
    | {
        value: string;
      }
    | ConfigVarExpression;
}) => {
  return {
    get component() {
      const context = requireIntegrationContext();
      return findUserDefinedComponentKey(
        "dropbox",
        true,
        context.componentRegistry,
      );
    },
    key: "dropboxWebhook",
    values,
  } as const;
};
