/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { dropboxWebhook } from "./dropboxWebhook";
import { pollChangesTrigger } from "./pollChangesTrigger";

export default {
  dropboxWebhook,
  pollChangesTrigger,
};
