/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { ConfigVarExpression } from "@prismatic-io/spectral";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type { Connection } from "@prismatic-io/spectral/dist/types";

export interface PollChangesTriggerValues {
  /**
   * Connection
   *
   */
  dropboxConnection: Connection;
  /**
   * Directory Path
   * The path to a directory within a Dropbox share. Include a leading \/.
   *
   * @example \/path\/to\/my\/directory\/
   * @placeholder Directory Path Prefix
   */
  directoryPath?: string;
  /**
   * Recursive
   * If true, the response will contain contents of all subfolders.
   *
   * @default false
   */
  recursive?: boolean;
  /**
   * Include Deleted?
   * If true, the results will include entries for files and folders that used to exist but were deleted.
   *
   * @default false
   */
  includeDeleted?: boolean;
  /**
   * Team User Type
   * The type of user to connect with. Admin or User.
   *
   */
  userType?: `admin` | `user` | ``;
  /**
   * Team Member ID
   * The ID of the team member. Required if Team User Type is set.
   *
   * @example dbmid:abcd1234
   */
  teamMemberId?: string;
}

/**
 * Checks for new and updated files on a configured schedule.
 *
 * @description Checks for new and updated files on a configured schedule.
 * This object is used to support type hinting.
 */
export const pollChangesTrigger = {
  key: "pollChangesTrigger",
  perform: <TReturn>(_values: PollChangesTriggerValues): Promise<TReturn> =>
    Promise.resolve<TReturn>({} as TReturn),
  inputs: {
    dropboxConnection: {
      inputType: "connection",
      collection: undefined,
      default: undefined,
      required: true,
    },
    directoryPath: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    recursive: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    includeDeleted: {
      inputType: "boolean",
      collection: undefined,
      default: `false`,
    },
    userType: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    teamMemberId: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
  },
} as const;

/**
 * Checks for new and updated files on a configured schedule. Trigger Helper
 *
 * @comments This wrapper function can be used directly in flow definitions.
 */
export const dropboxPollChangesTrigger = (values: {
  dropboxConnection:
    | {
        value: Connection;
      }
    | ConfigVarExpression;
  directoryPath?:
    | {
        value: string;
      }
    | ConfigVarExpression;
  recursive?:
    | {
        value: boolean;
      }
    | ConfigVarExpression;
  includeDeleted?:
    | {
        value: boolean;
      }
    | ConfigVarExpression;
  userType?:
    | {
        value: `admin` | `user` | ``;
      }
    | ConfigVarExpression;
  teamMemberId?:
    | {
        value: string;
      }
    | ConfigVarExpression;
}) => {
  return {
    get component() {
      const context = requireIntegrationContext();
      return findUserDefinedComponentKey(
        "dropbox",
        true,
        context.componentRegistry,
      );
    },
    key: "pollChangesTrigger",
    values,
  } as const;
};
