/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import actions from "./actions";
import connections from "./connections";
import dataSources from "./dataSources";
import triggers from "./triggers";

export { actions, connections, dataSources, triggers };

export default {
  key: "dropbox",
  public: true,
  signature: "887308b8f292bfd27bc98e3b390866a9d625d611",
  actions,
  dataSources,
  connections,
  triggers,
} as const;
