/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import actions from "./actions";
import connections from "./connections";
import dataSources from "./dataSources";
import triggers from "./triggers";

export { actions, connections, dataSources, triggers };

export default {
  key: "salesforce",
  public: true,
  signature: "046e531c50da859dafb17f0c63f3729cf37e24bd",
  actions,
  dataSources,
  connections,
  triggers,
} as const;
